name: 🐛Bug Report
description: File a bug report here
title: "[BUG]: "
labels: ["bug"]
assignees: ["hizuro"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: dropdown
    id: client-version
    attributes:
      label: WoW client
      description: What client flavor are you running?
      options:
        - WoW Retail
        - WoW TBC Classic
        - WoW Classic
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: false

  - type: textarea
    id: lua-error-message
    attributes:
      label: Lua Error Message?
      description: Please copy and paste any relevant lua error messages.
      render: lua
    validations:
      required: false

